### ISSUE TITLE
TableView cleanup ScrollBarProxy

### ISSUE THREAD

**Issue by encodedstephen** [fulmicoton/fattable#17]
I believe that the ScrollBarProxy cleanup doesn't work for the cleanup method in TableView (line 546 of fattable.coffee):

    cleanUp: ->
        # be nice rewind !
        @eventRegister.unbindAll()
        @ScrollBarProxy?.onScroll = null

After reading over the code, I believe that you were trying to do: 

    cleanUp: ->
        # be nice rewind !
        @eventRegister.unbindAll()
        @scroll?.onScroll = null

**Comment by PAEz** [comment]
really? ;)

**Comment by fulmicoton** [comment]
No I haven't >.<
Well I accept pull request :)

**Comment by fulmicoton** [comment]
Fixed in 833904c0ecff3b2ccf17c4a8e03b053b0b74a164
