### ISSUE TITLE
Is it possible to create table without knowing overall rows?

### ISSUE THREAD

**Issue by SamantaChinmoy** [fulmicoton/fattable#25]
Hello,
For example I have a tables of 1 million rows. So I want to draw table without setting nbRows = 1 millions.

**Comment by fulmicoton** [comment]
This is not possible. Right now you need to set nbRows

**Comment by SamantaChinmoy** [comment]
Actually I want to load data from database. So Knowing overall rows in database we have to run select count(*) which is taking a lot of times. So is there any alternative approach which can solve my problem?

**Comment by fulmicoton** [comment]
@SamantaChinmoy  Not that I know off.
